/**:
  ros__parameters:
    max_longitudinal_offset: 0.0 #3.2
    min_longitudinal_offset: 0.0 #1.8
    min_lateral_offset: 0.0 # -1.4
    max_lateral_offset: 0.0 # 1.4
    min_height_offset:  0.0 #0.8
    max_height_offset:  0.0 #1.5
