/**: #Clean_Robot #KMS_241009
  ros__parameters:
    wheel_radius: 0.32       # 바퀴의 반경
    wheel_width: 0.215        # 휠 타이어의 측면 너비
    wheel_base: 2.7          # 앞바퀴 <-> 뒷바퀴 사이 거리  #241011
    wheel_tread: 1.58  #REAR        # 왼쪽 바퀴 중심과 오른쪽 바퀴 중심 사이
    front_overhang: 0.86       # 앞바퀴 중심과 차량 전면 사이
    rear_overhang: 0.88        # 뒷바퀴 중심과 차량 후면 사이
    left_overhang: 0.23      # 왼쪽 바퀴 중심과 차량 왼쪽 사이
    right_overhang: 0.23     # 오른쪽 바퀴 중심과 차량 오른쪽 사이
    vehicle_height: 2.108
    max_steer_angle: 0.576 #30deg    # [rad] 
