/**:
  ros__parameters:
    wheel_radius: 0.32
    wheel_width: 0.205
    wheel_base: 2.57048 # between front wheel center and rear wheel center
    wheel_tread: 1.58 # between left wheel center and right wheel center
    front_overhang: 0.84 # between front wheel center and vehicle front
    rear_overhang: 0.73 # between rear wheel center and vehicle rear
    left_overhang: 0.23 # between left wheel center and vehicle left
    right_overhang: 0.23 # between right wheel center and vehicle right
    vehicle_height: 2.108 # vehicle(1.618) + lidar height(0.49)
    max_steer_angle: 0.576 # [rad]
